-- ======================================================================
-- Schema — restore this FIRST, then 02-data.sql
--
-- Generated by Polsia from your app database.
-- Source PostgreSQL : 16.15 (eb11870)
-- Source schema     : public
-- Snapshot taken at : 2026-10-01 11:54:05.118277+00
--
-- FOREIGN KEYS ARE NOT IN THIS FILE. They are at the end of 02-data.sql,
-- after the rows, so the data can load in any order.
-- ======================================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET DateStyle = 'ISO, MDY';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';
SET search_path TO public;

CREATE TABLE "Job" (
    id text NOT NULL,
    customer text NOT NULL,
    address text NOT NULL,
    "scheduledDate" text NOT NULL,
    crew text NOT NULL,
    status text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
ALTER TABLE "Job" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Job" ADD CONSTRAINT "Job_pkey" PRIMARY KEY (id);
CREATE INDEX "Job_scheduledDate_status_idx" ON "Job" USING btree ("scheduledDate", status);
CREATE INDEX "Job_status_scheduledDate_idx" ON "Job" USING btree (status, "scheduledDate");
