-- ======================================================================
-- Data — restore this AFTER 01-schema.sql
--
-- Generated by Polsia from your app database.
-- Source PostgreSQL : 16.15 (eb11870)
-- Source schema     : public
-- Snapshot taken at : 2026-10-01 11:54:05.118277+00
--
-- Foreign keys are added at the END of this file, once every row is in place,
-- so table and row order does not matter.
-- ======================================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET DateStyle = 'ISO, MDY';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';
SET search_path TO public;


-- Job
-- Give the planner statistics to work with.
ANALYZE;
